[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
	"php82",
	"php82Extensions.pdo",
	"php82Extensions.pdo_mysql",
	"php82Extensions.curl"
]

[deploy]
startCommand = "bash -lc 'php -S 0.0.0.0:$PORT'"
